### ISSUE TITLE
Any Way To optimize the ClickHouseCommand memory Use

### ISSUE THREAD

**Issue by xibaoning** [killwort/ClickHouse-Net#152]
block execute 500000 rows  memory use 500-600M
```C#

//ClickHouse.Ado.ClickHouseCommand
private void Execute(bool readResponse, ClickHouseConnection connection){
	var cl = new List<List<object>>(colCount);
	for (var i = 0; i < colCount; i++)
		cl.Add(new List<object>());   //chagne to  new List<object>(rowcount); ???  or ArrayPool ???
		
	//....
	 foreach (var col in schema.Columns) col.Type.ValuesFromConst(cl[index++]);
}

//ClickHouse.Ado.Impl.ColumnTypes.ArrayColumnType
public override void ValuesFromConst(IEnumerable objects) {
		var offsets = new List<ulong>(); //new List<ulong>(rowcount);  ???   or ArrayPool ???
		var itemsPlain = new List<object>(); //new List<ulong>(rowcount);  ???   or ArrayPool ???
	   //....
  }
```

OR

public interface for user ?

**Comment by killwort** [comment]
Sadly memory usage cannot be easily improved. That's because you supply row-based data to insert (or expect row-based data on select) and clickhouse needs/provides column-based data, so the driver must convert it on the fly and must do it for the whole recordset at once.
Your changes cannot be applied because insert parameter value is treated as `IEnumerable<IEnumerable<object>>`, so the `Count()` call will enumerate collections second time with possible side effects.
You could probably use IBulkInsertEnumerable which can decrease memory consumption on INSERTs although it still allocates memory for internal column data representation.
