### ISSUE TITLE
Insert Parser fails execution of INSERT queries without the term VALUES

### ISSUE THREAD

**Issue by DenZhuv** [killwort/ClickHouse-Net#175]
## Description
When attempting to execute an INSERT query where does not require specifying VALUES, the operation fails. No data is inserted, and no error messages are generated.

I need to execute queries like
``` SQL
INSERT INTO FUNCTION
remoteSecure(...)
SELECT somefields FROM sometalbe
```
but there is no result of executing of the query.

v2.0.5

## How to reproduce
Execute the following query with construction from example.

## What should be done
It would be very useful to have support for alternative INSERT queries, without a "bulk" parameter and VALUES term, at least so that they are executed "as is".

**Comment by flippingbook** [comment]
I've added test in last commit and everything works as expected. INSERTs which could not be parsed with grammar (e.g. insert into table function) are executed as is. However note that they should not be executed with ExecuteReader or ExecuteScalar - they do not return any data and exepectedly fail when trying to read beyond end of stream. Moreover, ExecuteNonQuery does not return number of inserted rows because clickhouse server does not bother itself with giving that value via native protocol.

**Comment by killwort** [comment]
I've added test in last commit and everything works as expected. INSERTs which could not be parsed with grammar (e.g. insert into table function) are executed as is. However note that they should not be executed with ExecuteReader or ExecuteScalar - they do not return any data and exepectedly fail when trying to read beyond end of stream. Moreover, ExecuteNonQuery does not return number of inserted rows because clickhouse server does not bother itself with giving that value via native protocol.

**Comment by DenZhuv** [comment]
I just ran my code again, which wasn't working when I wrote the problem. And... it worked. 
(╯°□°）╯︵ ┻━┻

Apologies for the unnecessary trouble.
