### ISSUE TITLE
Insert into values via ExecuteNonQuery bug

### ISSUE THREAD

**Issue by Fallenyasha** [killwort/ClickHouse-Net#88]
There is incorrect parse of arrays when I trying to insert via ExecuteNonQuery
"INSERT INTO table (vals) VALUES (['test'])"
This query works, but insert quoted value in table, not just < test >, but < 'test' >

Query "INSERT INTO table (vals) VALUES (array('test'))" not works, it freezes.

**Comment by killwort** [comment]
You shouldn't be using literal insert syntax. Either use insert with parametrized values, or even better - use bulk inserts.

Due to clickhouse native protocol 'specialty' (different forms of INSERT commands require different communication) the driver needs to fully parse INSERT commands and I'm too lazy to implement full SQL92 compatible parser for it. Plus literal inserts are not recommended by the clickhouse team.
